enum AppCommand {
  focusSearch,
  toggleHistory,
  nextVerse,
  prevVerse,
  addNextVerseToSelection,
  removeVerseFromSelection,
  changeBible,
  nextPane,
  prevPane,
  addParallelPane,
  closeCurrentPane,
  movePaneToRight,
  movePaneToLeft,
  toggleMenubar,
  toggleToolbar,
  toggleFullscreen,
  switchDisplayMode,
  zoomIn,
  zoomOut,
  // private shortcuts
  // do not show as shortcut in the app
  unfocusSearch,
  displayChapterOfSelected,
}
