enum AppCommand {
  focusSearch,
  toggleHistory,
  nextVerse,
  prevVerse,
  addNextVerseToSelection,
  removeVerseFromSelection,
  changeBible,
  nextPane,
  prevPane,
  addPane,
  removePane,
  movePaneToRight,
  movePaneToLeft,
  toggleToolbar,
  toggleFullscreen,
  switchDisplayMode,
  zoomIn,
  zoomOut,
  flushOverlayBuffer,
  // private shortcuts
  // do not show as shortcut in the app
  closeWhatever,
  displayChapterOfSelected,
}
