// Mocks generated by Mockito 5.4.4 from annotations
// in the_smyrna_bible_v2/test/features/translation_reader/domain/usecases/read_usfx_translation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:the_smyrna_bible_v2/core/error/failure.dart' as _i5;
import 'package:the_smyrna_bible_v2/features/bible_display/translation_reader/domain/repositories/reader_repository.dart'
    as _i2;
import 'package:the_smyrna_bible_v2/features/translations_installer_manager/domain/entities/translation.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ReaderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReaderRepository extends _i1.Mock implements _i2.ReaderRepository {
  MockReaderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Translation>> getTranslation(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslation,
          [id],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.Translation>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i6.Translation>>(
          this,
          Invocation.method(
            #getTranslation,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.Translation>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> removeTranslation(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTranslation,
          [id],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #removeTranslation,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
