// Mocks generated by Mockito 5.4.4 from annotations
// in the_smyrna_bible_v2/test/core/models/translation_manager_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:the_smyrna_bible_v2/core/models/translation_manager_model.dart'
    as _i2;
import 'package:the_smyrna_bible_v2/features/translations_installer_manager/domain/entities/translation.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TranslationManagerModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranslationManagerModel extends _i1.Mock
    implements _i2.TranslationManagerModel {
  MockTranslationManagerModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i3.Translation> get localTranslations => (super.noSuchMethod(
        Invocation.getter(#localTranslations),
        returnValue: <String, _i3.Translation>{},
      ) as Map<String, _i3.Translation>);

  @override
  set localTranslations(Map<String, _i3.Translation>? _localTranslations) =>
      super.noSuchMethod(
        Invocation.setter(
          #localTranslations,
          _localTranslations,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Translation? getUsfxTranslation(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getUsfxTranslation,
        [id],
      )) as _i3.Translation?);

  @override
  bool closeUsfxTranslation(String? id) => (super.noSuchMethod(
        Invocation.method(
          #closeUsfxTranslation,
          [id],
        ),
        returnValue: false,
      ) as bool);
}
